### PR TITLE
A little mental stretch for the AM

### PR DESCRIPTION
**Pull request by NathanBland**
Its interesting to me that your test doesn't like the loop starting with zero... A fair thing to ask for I guess, as `0 % 3` isn't going to ever be useful to anyone, but it did break my code the first time.

### CODE REVIEW

**Comment by barberboy** [comment]
Haha, yes. I don’t know why exactly I chose to 1-100 instead of 0-100. Was
the error message helpful for you or too opaque?

**Comment by NathanBland** [comment]
I think its clear enough, as it shows what numbers should be there..
An interesting result of my code now though, is if I change the loop to
start at 0 instead of 1 it results in
```javascript
AssertionError: Expected 'FizzBuzz' to be '1' on line 1.
    at /home/nathan/Projects/node/webtech/fizzbuzz/test/index.js:21:20
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```
which is technically true, because `0 % 3 === 0` and the same for `5`. So
perhaps starting at 1 isn't such a bad idea after all.

**Comment by NathanBland** [comment]
I think its clear enough, as it shows what numbers should be there..
An interesting result of my code now though, is if I change the loop to
start at 0 instead of 1 it results in

``` javascript
AssertionError: Expected 'FizzBuzz' to be '1' on line 1.
    at /home/nathan/Projects/node/webtech/fizzbuzz/test/index.js:21:20
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

which is technically true, because `0 % 3 === 0` and the same for `5`. So perhaps starting at 1 isn't such a bad idea after all.

**Comment by barberboy** [comment]
:+1: Looks great! Yeah, zero resolving to "FizzBuzz" is interesting and non-intuitive.

I think this is the first submission that avoids an explicit check for `(i % 3 === 0 && i % 5 === 0)`.

If you wanted to avoid creating the `str` variable and didn't mind taking full advantage of JavaScript's definition of "truth" (`0` and `''` (an empty string) both are "falsy") you could do something like this:

``` js
console.log((n % 3 ? '' : 'Fizz') + (n % 5 ? '' : 'Buzz') || n)
```

I'm not a big fan of "code golf", but I do like this 👆FizzBuzz implementation.

**Pull request closed without merging**
